### PR TITLE
 Fix  #28 -- Update Python and Django versions

### LINKED ISSUE #28: Update Python and Django versions

### PR DESCRIPTION
**Pull request by pauloxnet**
Ref #28

### CODE REVIEW

**Comment by pauloxnet** [comment]
@epicserve can you unlock the Python 3.7 required step and review this PR

**Comment by epicserve** [comment]
@pauloxnet, do we really need to have checks for so many permutations of Django and Python? Especially versions of Django that are [no longer supported](https://www.djangoproject.com/download/) and versions of Python that are [no longer supported](https://devguide.python.org/versions/#versions).

**Comment by epicserve** [comment]
@pauloxnet, I'm not seeing an obvious way to unlock Python 3.7 tests from running.

**Comment by pauloxnet** [comment]
> @pauloxnet, do we really need to have checks for so many permutations of Django and Python? Especially versions of Django that are [no longer supported](https://www.djangoproject.com/download/) and versions of Python that are [no longer supported](https://devguide.python.org/versions/#versions).

As for the permutations, I would leave all those Django/Python supported versions

If you are referring to Django 4.1 EOL, when I opened the PR it was still supported :-D

Python 3.8 however will still be supported until October 2024

Given today's releases, I will update this PR

**Comment by pauloxnet** [comment]
> @pauloxnet, I'm not seeing an obvious way to unlock Python 3.7 tests from running.

I think it's because I removed Python 3.7.

Where "un Python 3.7 tests " is defined as "required"? In the code or the repo settings?

**Comment by pauloxnet** [comment]
@epicserve you were faster than me. Thanks for the release

**Pull request merged**
